<a href="https://colab.research.google.com/github/jeff-ai-ml/bronze-badge-project/blob/main/product_ad_sales_regression_linear_regression_frameworks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Can you build a multivariate linear regression model that can predict the product sales based on the advertising budget allocated to different channels. The features are TV Budget ($),Radio Budget ($),Newspaper Budget ($) and the output is Sales (units)


# step 1: import the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# step 2: reading the data and splitting it to input and output


In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/jeff-ai-ml/ml-datasets/refs/heads/main/product_ad_sales.csv')

print(dataset)
inputx = dataset.iloc[:, :-1].values
outputy = dataset.iloc[:, 3].values

print(inputx)
print(outputy)



   TV Budget ($)  Radio Budget ($)  Newspaper Budget ($)  Sales (units)
0          230.1              37.8                  69.2           22.1
1           44.5              39.3                  45.1           10.4
2           17.2              45.9                  69.3            9.3
3          151.5              41.3                  58.5           18.5
4          180.8              10.8                  58.4           12.9
5            8.7              48.9                  75.0            7.2
6           57.5              32.8                  23.5           11.8
7          120.2              19.6                  11.6           13.2
8          144.1              16.0                  40.3           15.6
9          111.6              12.6                  37.9           12.2
[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]
 [  8.7  48.9  75. ]
 [ 57.5  32.8  23.5]
 [120.2  19.6  11.6]
 [144.1  16.   40.3]
 [111.6  12.6  37.9

In [3]:
#print(dataset)

# step 3: select one thirds of the data for testing and two thirds for training

In [4]:
input_train, input_test, output_train, output_test = train_test_split(inputx, outputy, test_size = 1/4, random_state = 7)

# step 4: selecting the simple Linear Regression model

In [6]:
model = LinearRegression()
print("\nThe parameters of the model are\n\n",model.get_params())

print("\nThe model we are using is ", model.fit(input_train, output_train))




The parameters of the model are

 {'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

The model we are using is  LinearRegression()


# step 5: testing or model prediction using testinput

In [8]:
print("Hello! I can predict the number of units that will be sold if you give the budget/spending on ads given on TV, Radio, News")
tv = float(input("Enter your TV ad budget or spendings : "))
news_paper =float(input("Enter your News Paper ad budget or spendings : "))
radio = float(input("Enter your Radio ad budget or spendings : "))
testinput = [[tv, news_paper, radio]]
predicted_output = model.predict(testinput)
print('\nThe Budget or Spending on various ads [TV, News Paper, Radio] is ',testinput)
print('\nThe Sales (units) of the prodcut is is ',predicted_output)
#yes = input("\nCan I proceed\n")

Hello! I can predict the number of units that will be sold if you give the budget/spending on ads given on TV, Radio, News
Enter your TV ad budget or spendings : 230
Enter your News Paper ad budget or spendings : 38
Enter your Radio ad budget or spendings : 69

The Budget or Spending on various ads [TV, News Paper, Radio] is  [[230.0, 38.0, 69.0]]

The Sales (units) of the prodcut is is  [21.78808855]


# step 6: Printing the testing results

In [25]:
print("\nThe test input Ad Budget for TV, News Paper and Radio are as follows \n")
print(input_test)
# model predicting the Test set results
predicted_output = model.predict(input_test)
print("\nThe output (Units Sold) for the test input is as follows \n")
print(predicted_output)


The test input Ad Budget for TV, News Paper and Radio are as follows 

[[144.1  16.   40.3]
 [  8.7  48.9  75. ]
 [230.1  37.8  69.2]]

The output (Units Sold) for the test input is as follows 

[13.34141541  9.15436676 21.74734019]
